# Generated by Django 2.0.6 on 2018-09-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kworb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastestRisingOnRadio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField(default='00000000')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworb.Song')),
            ],
        ),
        migrations.CreateModel(
            name='NewOnRadio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField(default='00000000')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworb.Song')),
            ],
        ),
        migrations.CreateModel(
            name='TopFiveRadio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField(default='00000000')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kworb.Song')),
            ],
        ),
        migrations.CreateModel(
            name='TopFiveSpins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_stamp', models.DateField(default='00000000')),
                ('song', models.ManyToManyField(to='kworb.Song')),
            ],
        ),
        migrations.CreateModel(
            name='TopFiveSpotify',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist', models.TextField(blank=True, default='null', max_length=200, null=True)),
                ('title', models.TextField(blank=True, default='null', max_length=200, null=True)),
                ('plays', models.IntegerField()),
                ('date_stamp', models.DateField(default='00000000')),
            ],
        ),
    ]
